dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: sonya-go0308
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.13
- name: sonya-spring0319
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: voting-result
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: voting-vote
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.10
- name: voting-worker
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.2
